import = ["/home/bytecrack/.config/alacritty/themes/themes/dark_pastels.toml", "/home/bytecrack/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "None"
dynamic_title = false
opacity = 0.9
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 70

[window.padding]
x = 7
y = 7

